### PR TITLE
Add bulk merge feature

### PR DESCRIPTION
**Pull request by gideruette**
Allow to bulk merge :

- Create new temporary table
- Copy data in this temporary table
- Upsert data from temporary table to target table
- Drop temporary table

To use bulk merge, you must define primary key in mapping (AbstractMergeMapping)

### CODE REVIEW

**Comment by bytefish** [comment]
I see your need for the feature and I see, that you have put a lot of energy into it. I also understand it's a feature, that makes your life a lot easier. As a maintainer it's hard to decline PRs from people collaborating on the project. But this library has a focus on the COPY Protocol, and supporting upserts is a different area, which could come with its own set of problems, that are going to be hard to debug and would take time, I don't have.

So sorry, I am closing it and hope you do understand my reasons.

**Comment by gideruette** [comment]
I understand, thantks for review :)
The upsert feature will be available in this lib : https://github.com/klee-contrib/spring-batch-bulk

**Comment by bytefish** [comment]
What I would do these days is something like this: 

* https://www.bytefish.de/blog/bulk_updates_postgres.html

I wouldn’t define a custom type anymore, but just pass the data as JSON and unnest it in the procedure. This way you don’t need to define staging tables, and you are flexible when it comes to updates.

I didn’t evaluate properly how near this gets to the performance of a Binary COPY, but I think it is quite an efficient approach.

**Comment by gideruette** [comment]
I understand the disadvantages of creating temporary table. But in my case, I generate mapping description with a great model generator [TopModel](https://github.com/klee-contrib/topmodel). Incoming dataflow feature...

About performance, I've inserted 40,000,000 (small) lines in 5 minutes locally, so it's ok for my needs.

**Pull request closed without merging**
