### PR TITLE
Upgrade postgresql jdbc version to latest.

### PR DESCRIPTION
**Pull request by umartin**
Upgrade postgresql jdbc version to latest. There are several know vulnerabilities in older version.

### CODE REVIEW

**Comment by bytefish** [comment]
Thanks for your PRs. I will do my part and release an updated version to Maven as soon as possible! 👍

**Comment by umartin** [comment]
Thanks! And thank you for a great library!

**Comment by bytefish** [comment]
@umartin Sorry it took so long. I had to find out my Maven Central Repositories passwords first 😓. It should be available soon. I've also removed the Checker Framework and all its code, because as long as the language doesn't check it for me... I don't want to manage yet another dependency.

**Comment by umartin** [comment]
Good call! I see know that the new version of Checker Framework brought in by the new postgresql version broke the build. Sorry about that.

**Comment by bytefish** [comment]
No worries, I wanted to remove it anyway. The less dependencies, the better. 👍

**Pull request merged**
